### ISSUE TITLE
Markdown widget in build report not displaying tables correctly

### ISSUE THREAD

**Issue by renevanosnabrugge** [andremarques023/vsts-extensions#29]
Hi,

I used the widget in my build and it works great ! But the table is not rendered like I am used to in GitHub. 
 The headers are centered and rows are not displayed with alternate colors and borders but just as text..

Is this something that can be fixed or is it in the rendering of the build report?

I use this table

| Filename | Source | Product | Type |
| --- | --- | --- | --- |
| tst.txt | c:\tmp\file.txt | product1 | BUILD |

Thanks!

**Comment by andremarques023** [comment]
Hi Rene,

I'll take a look later. Thank you for your feedback!

**Comment by andremarques023** [comment]
I've checked and it's probably just the way it renders the summary. However, you can still use HTML to define style. Please, take a look at the SonarQube for MSBuild task to see how it uses HTML to output the Quality Gate status in the Build Summary page:

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SonarQubePostTest/SummaryReport/QualityGateSection.ps1
